In [2]:
import pandas as pd

In [4]:
data = pd.read_csv('train_data.csv')
data

,Unnamed: 0,Age,Gender,Stage,GeneticRisk,TreatmentType,ComorbidityIndex,TreatmentResponse,SurvivalTime,Censored
0,0,65.0,0,2,1.0,0,0.0,0.0,4.2,0
1,1,68.0,1,2,0.0,1,1.0,1.0,4.7,1
2,2,68.0,1,3,1.0,1,0.0,1.0,3.5,1
3,3,81.0,1,4,1.0,1,3.0,0.0,2.3,0
4,4,59.0,1,2,1.0,0,NaN,0.0,NaN,0
...,...,...,...,...,...,...,...,...,...,...
395,395,66.0,0,3,0.0,1,0.0,1.0,NaN,0
396,396,72.0,1,2,NaN,0,2.0,1.0,7.2,0
397,397,69.0,0,2,0.0,0,1.0,1.0,NaN,0
398,398,63.0,0,4,0.0,1,2.0,1.0,8.1,0
399,399,67.0,0,2,0.0,1,0.0,0.0,3.7,0

## Task 1